apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-api
  labels:
    app: comment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-api
  template:
    metadata:
      labels:
        app: comment-api
    spec:
      containers:
        - name: comment-api
          image: docker.io/library/comment-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
