apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
  labels:
    app: post-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
        - name: post-api
          image: docker.io/library/post-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
