apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-log"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
