apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-user-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-user" # A unique path for user-specific data
