apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-comment-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-comment"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-comment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
