apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-logs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
