apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Will be removed 
  type: NodePort # when gateway is done