apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
spec:
  selector:
    app: user-api
  ports:
    - appProtocol: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
