apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  containers:
    - name: comments
      # image: path <--TODO
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
  selector:
    app: comments
  ports:
    - appProtocol: http
      protocol: TCP
      port: 8080
      targetPort: 8080