apiVersion: apps/v1
kind: Deployment
metadata:
  name: useridentityapi-deployment
  labels:
    app: useridentityapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: useridentityapi
  template:
    metadata:
      labels:
        app: useridentityapi
    spec:
      containers:
        - name: useridentityapi
          image: docker.io/discosam/userimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: "rabbit-service"
            - name: RABBITMQ_PORT
              value: "5672"
