apiVersion: apps/v1
kind: Deployment
metadata:
  name: useridentityapi-deployment
  labels:
    app: useridentityapi # Add label here
spec:
  replicas: 3
  selector:
    matchLabels:
      app: useridentityapi
  template:
    metadata:
      labels:
        app: useridentityapi # Consistent label here as well
    spec:
      containers:
        - name: useridentityapi
          image: docker.io/discosam/userimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
