apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672   # RabbitMQ meddelandehanteringsport
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672  # RabbitMQ Management UI-port
      targetPort: 15672
  type: NodePort  # Gör tjänsten tillgänglig via en nodport
