apiVersion: v1
kind: Service
metadata:
  name: postgres-log-svc
spec:
  selector:
    app: postgres-log
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Makes sure the service cannot receive external requests

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-log
  labels:
    app: postgres-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-log
  template:
    metadata:
      labels:
        app: postgres-log
    spec:
      containers:
      - name: postgres-log
        image: postgres
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-log-pv
      volumes: #Register volume and volume claim
      - name: postgres-log-pv
        persistentVolumeClaim:
          claimName: postgres-log-pvc
