apiVersion: v1
kind: Service
metadata:
  name: postgres-user-svc
spec:
  selector:
    app: postgres-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  labels:
    app: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-user-pv
      volumes:
        - name: postgres-user-pv
          persistentVolumeClaim:
            claimName: postgres-user-pvc
