apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: search-route
spec:
  parentRefs:
  - name: prod-web
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /search
    backendRefs:
    - name: search-api-svc
      port: 9201
